# Generated by Django 5.2.7 on 2025-11-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.TextField(max_length=250)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fechaAct', models.DateField(blank=True, null=True)),
                ('mensaje', models.TextField(max_length=250)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_adjuntos/')),
            ],
        ),
    ]
