# Generated by Django 5.2.7 on 2025-11-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalAdoptable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('especieid', models.TextField()),
                ('edad', models.TextField()),
                ('salud', models.TextField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='cargos')),
                ('pdf', models.FileField(blank=True, upload_to='pdfs')),
            ],
        ),
    ]
