# Generated by Django 5.2.7 on 2025-11-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaladoptable',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'DISPONIBLE'), ('ADOPTADO', 'ADOPTADO')], default='DISPONIBLE', max_length=15),
        ),
        migrations.AddField(
            model_name='animaladoptable',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
