# Generated by Django 5.2.7 on 2025-11-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0002_animaladoptable_estado_animaladoptable_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaladoptable',
            name='precio',
            field=models.CharField(default='0.00', max_length=20),
        ),
    ]
