# Generated by Django 5.2.7 on 2025-11-06 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0003_alter_animaladoptable_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaladoptable',
            name='precio',
        ),
    ]
