# Generated by Django 5.2.7 on 2025-11-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animales', '0004_remove_animaladoptable_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='animaladoptable',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
