# Generated by Django 5.2.7 on 2025-11-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoptantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptante',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='adoptante',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
