# Generated by Django 5.2.7 on 2025-11-06 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adoptantes', '0002_adoptante_correo_adoptante_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptante',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='adoptante',
            name='password',
        ),
    ]
