# Generated by Django 5.2.7 on 2025-11-06 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adoptantes', '0004_adoptante_usuario'),
        ('Login', '0002_registrar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptante',
            name='usuario',
        ),
        migrations.AddField(
            model_name='adoptante',
            name='registro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.registrar'),
        ),
    ]
