# Generated by Django 5.2.7 on 2025-11-03 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adoptantes', '0001_initial'),
        ('Animales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('pago', models.TextField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='cargos')),
                ('pdf', models.FileField(blank=True, upload_to='pdfs')),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoptantes.adoptante')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animales.animaladoptable')),
            ],
        ),
    ]
