# Generated by Django 5.2.7 on 2025-11-03 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adoptantes', '0001_initial'),
        ('Animales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adoptantes.adoptante')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Animales.animaladoptable')),
            ],
        ),
    ]
