# Generated by Django 5.2.7 on 2025-11-07 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdopcionU', '0001_initial'),
        ('Login', '0002_registrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudadopcion',
            name='registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Login.registrar'),
        ),
    ]
